### ISSUE TITLE
How to choose another colour for transparency

### ISSUE THREAD

**Issue by frak** [python-ugame/circuitpython-stage#12]
Hi, I want to load some sprites that use magenta in them but as per the tutorial this colour is reserved for transparency. Is there any way to specify a different colour to use for transparency?

I can't seem to see any special cases in the `Bank` class for this colour so I can only assume that this is being handled in the C code which I don't know where to find.

**Comment by deshipu** [comment]
No, there is no way to change it. You can make your sprites use a slightly different color — for human eye the difference is not noticeable.
