### ISSUE TITLE
pyBadge LC hangs when import ugame

### ISSUE THREAD

**Issue by OutOfTheBots** [python-ugame/circuitpython-stage#17]
firmware on the pybadge LC is "adafruit-circuitpython-pybadge-en_US-7.0.0.uf2"

I can type "import stage" and it imports fine the returns to repl but when I type "import ugame" into the repl prompt the pybadge screen goes black and it hangs never returning back to the repl and I can no longer access the files system via window file explorer.

**Comment by deshipu** [comment]
This is because ugame calls `release_displays` and re-initializes the display, and this is currently broken in CP 7.0, see https://github.com/adafruit/circuitpython/issues/5476

**Comment by OutOfTheBots** [comment]
Thank you for your prompt responce

**Comment by deshipu** [comment]
This is now worked around in CircuitPython 7.1.0-beta.1.
