### ISSUE TITLE
Non-sprite based drawing

### ISSUE THREAD

**Issue by timbledum** [python-ugame/circuitpython-stage#2]
Hi!

Is there any way to draw lines or pixels directly in ugame without using images / sprites?

**Comment by deshipu** [comment]
No, sorry. The hardware limitations meant that some trade-offs had to be made. The microcontroller doesn't have enough memory to hold information about all those pixels — the data sent to the display is generated as it it sent, from the tile maps and sprites. I was thinking about adding the possibility of loading a whole-screen bitmap (basically also reading it and sending directly to the display) for things like splash screens and such, but that couldn't be mixed with the tiles and sprites.

**Comment by timbledum** [comment]
Thanks for that – good to know!
