### ISSUE TITLE
How do palettes work?

### ISSUE THREAD

**Issue by gmeader** [python-ugame/circuitpython-stage#8]
How do I create the data for a custom palette? 
Is there documentation on how palettes work (what do the bytes in a palette mean)?

**Comment by deshipu** [comment]
They are RGB565 colors: first five bits are red component, the next six bits are the green component, and the last five bits are the blue component. You can get those numbers using the color565 function https://circuitpython-stage.readthedocs.io/en/latest/README.html#stage.color565, but I think the best approach is to load the palette from an image, and print its repr, then use that as a black box. Hope that helps.
